### PR TITLE
Fix version tolerance when bad assembly version specified in type manifest

### LINKED ISSUE #144: Version tolerance
```
System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.2.0, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Collections.Immutable, Version=1.2.2.0, PublicKeyToken=b03f5f7f11d50a3a'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Hyperion.Extensions.TypeEx.<>c.<GetTypeFromManifestName>b__27_0(ByteArrayKey b)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Hyperion.Extensions.TypeEx.GetTypeFromManifestName(Stream stream, DeserializerSession session)
   at Hyperion.Extensions.TypeEx.GetTypeFromManifestVersion(Stream stream, DeserializerSession session)
   at Hyperion.Serializer.GetDeserializerByManifest(Stream stream, DeserializerSession session)
   at lambda_method(Closure , Stream , DeserializerSession )
   at Hyperion.Serializer.Deserialize[T](Stream stream)
   at Akka.Serialization.HyperionSerializer.FromBinary(Byte[] bytes, Type type)
```
@Aaronontheweb  should nodes with different versions of a package like `System.Collections.Immutable` break remoting serialization?

### PR DESCRIPTION
**Pull request by IgorFedchenko**
Close #144 

The basic idea is to ignore assembly version, if it is specified in incoming message type's manifest.

### CODE REVIEW

File: src/Hyperion/Extensions/TypeEx.cs [hunk 1]
```diff
@@ -130,11 +130,26 @@ private static Type GetTypeFromManifestName(Stream stream, DeserializerSession s
...
                 }
 #endif
+                return LoadTypeByName(shortName);
+            });
+        }
 
-                var typename = ToQualifiedAssemblyName(shortName);
+        public static Type LoadTypeByName(string name)
+        {
+            try
```
Comment (IgorFedchenko) [inline src/Hyperion/Extensions/TypeEx.cs]: Initially I was going to just ignore assembly version, if specified.

But actually this may bring some issues in cases when there are multiple assembly versions available for loading (i.e. one available in GAC and another available locally), and older version of serializes are used on remote end, so it is passing assembly version.

So let's say if I am using old Akka.NET serializer on `node1` and I am updating Hyperion version on `node2`, and `node1` tells to use version `1.0.0.0` but I have `2.0.0.0` in GAC and `1.0.0.0` locally - I will get type loaded from `2.0.0.0`, and this may break something.  
While after updating serializer on remote end I will get this conflicts anyway (because assembly version will be missing and `2.0.0.0` will be loaded anyway) - this is not related to Hyperion, and I think we should keep backwards capability if possible.

The only drawback here is that throwing/catching exception may be expensive in terms of performance - but this should be fine, since exception will be thrown/catched only in cases when if was crashing before, and you can always improve performance by updating serializers to latest versions.

File: src/Hyperion/Extensions/TypeEx.cs [hunk 2]
```diff
@@ -228,9 +243,18 @@ public static string GetShortAssemblyQualifiedName(this Type self)
...
+            
+            // Strip out assembly version, if specified
+            if (ignoreAssemblyVersion)
+            {
+                var versionSubstrIndex = res.IndexOf(", Version=", StringComparison.Ordinal);
+                if (versionSubstrIndex >= 0)
+                    res = res.Remove(versionSubstrIndex);
+            }
+            
             return res;
```
Comment (ismaelhamed) [inline src/Hyperion/Extensions/TypeEx.cs]: Stripping out the assembly version doesn't seem to be quite working. For a shortName: 

```System.Collections.Immutable.ImmutableDictionary`2[[System.String, mscorlib,%core%],[System.Int32, mscorlib,%core%]], System.Collections.Immutable, Version=1.2.1.0, PublicKeyToken=b03f5f7f11d50a3a```

 the output is: 

```System.Collections.Immutable.ImmutableDictionary`2[[System.String, mscorlib```

Comment (Aaronontheweb) [reply src/Hyperion/Extensions/TypeEx.cs]: cc @IgorFedchenko

Comment (IgorFedchenko) [reply src/Hyperion/Extensions/TypeEx.cs]: @ismaelhamed Huh, good catch, thanks!
Did not notice that %core% is replaced to something, that contains "Version=..." too.
Fixed, and added test case for this as well.

Comment (ismaelhamed) [reply src/Hyperion/Extensions/TypeEx.cs]: Working now @IgorFedchenko , thanks!

Comment (ismaelhamed) [reply src/Hyperion/Extensions/TypeEx.cs]: Actually I've encounter another case in which it fails:

```
System.Collections.Immutable.ImmutableList`1[[Foo.Bar, Foo, Version=2019.12.10.1]], System.Collections.Immutable, Version=1.2.2.0, PublicKeyToken=b03f5f7f11d50a3a
```

will also remove the `]]` along with the Version:

```
System.Collections.Immutable.ImmutableList`1[[Foo.Bar, Foo
```

Maybe too many edge cases to trying stripping the Version manually?

Comment (IgorFedchenko) [reply src/Hyperion/Extensions/TypeEx.cs]: @ismaelhamed Hmm, well, stripping Version as a substring was definitely bad idea.

Let's make it more careful, and strip it by regex. I will use `new Regex(@",[\s]*Version=[0-9\.]*")`, should work for any valid `Version` entry.

Except manual version stripping, the only way I know is hacking the next step - assembly loading. We could subscribe to [`AssemblyLoadContext.Resolving`](https://docs.microsoft.com/ru-ru/dotnet/api/system.runtime.loader.assemblyloadcontext.resolving?view=netcore-3.1) event and try to ignore assembly version from there. And remove subscription once type is resolved. But this is more complex approach which requires careful handling, because this event subscription is global for application and if we will miss unsubscription (i.e. due to some local handled exception), we will have all assemblies always loaded with version ignoring. Which might be not critical, but jet.

So, this is just an idea - actually cutting off `,(spaces)Version=(numbers and dots)` should cover cases I can imagine.

But @ismaelhamed thank you very much for been so attentive!

Comment (ismaelhamed) [reply src/Hyperion/Extensions/TypeEx.cs]: @IgorFedchenko I was thinking it should probably be a good idea to make that Regex static, and I just realized there's already a `cleanAssemblyVersionRegex` in this file.

Comment (IgorFedchenko) [reply src/Hyperion/Extensions/TypeEx.cs]: @ismaelhamed Indeed, there is an existing regex that is used to strip assembly version before serializing types. Thanks again, this looks even better now :)
