### PR TITLE
Fix settings constructor backward compatibility issue

### LINKED ISSUE #212: Hyperion 0.10.0 breaks akka.net compatibility
Hyperion 0.10.0 breaks akka.net compatibility where as 0.9.17 works fine

     System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.MissingMethodException: Method not found: 'Void Hyperion.SerializerOptions..ctor(Boolean, Boolean, System.Collections.Generic.IEnumerable`1<Hyperion.Surrogate>, System.Collections.Generic.IEnumerable`1<Hyperion.SerializerFactories.ValueSerializerFactory>, System.Collections.Generic.IEnumerable`1<System.Type>, Boolean)'.
         at Akka.Serialization.HyperionSerializer..ctor(ExtendedActorSystem system, HyperionSerializerSettings settings)
         at Akka.Serialization.HyperionSerializer..ctor(ExtendedActorSystem system)
         --- End of inner exception stack trace ---
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
         at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
         at Akka.Serialization.Serialization..ctor(ExtendedActorSystem system)
         at Akka.Actor.Internal.ActorSystemImpl.ConfigureSerialization()
         at Akka.Actor.Internal.ActorSystemImpl..ctor(String name, Config config, ActorSystemSetup setup, Nullable`1 guardianProps)
         at Akka.Actor.ActorSystem.CreateAndStartSystem(String name, Config withFallback, ActorSystemSetup setup)
         at Akka.Actor.ActorSystem.Create(String name, Config config)

### PR DESCRIPTION
**Pull request by Arkatufus**
Closes  #212

### CODE REVIEW

File: src/Hyperion/SerializerOptions.cs [hunk 1]
```diff
@@ -72,7 +80,25 @@ public class SerializerOptions
         internal readonly List<Func<string, string>> CrossFrameworkPackageNameOverrides =
             DefaultPackageNameOverrides();
 
-        public SerializerOptions(bool versionTolerance = false, bool preserveObjectReferences = false, IEnumerable<Surrogate> surrogates = null, IEnumerable<ValueSerializerFactory> serializerFactories = null, IEnumerable<Type> knownTypes = null, bool ignoreISerializable = false, IEnumerable<Func<string, string>> packageNameOverrides = null)
+        [Obsolete]
+        public SerializerOptions(
```
Comment (Arkatufus) [inline src/Hyperion/SerializerOptions.cs:84]: This is the old constructor, added back in for backward compatibility issue.
New constructor broke backward compatibility because it was called using reflection and `Activator` class.

Comment (Aaronontheweb) [reply src/Hyperion/SerializerOptions.cs:84]: IMHO, this is part of the problem with using optional parameters everywhere - very difficult to properly version the constructor when that happens. That's a design we inherited, but we might want to rethink that.

**Review by Aaronontheweb — CHANGES_REQUESTED** [review]
Can you add an Akka.NET integration test that verifies that Hyperion can be loaded correctly inside Akka.Serialization.Hyperion? Might be worth adding a new test project for that purpose.

**Comment by Arkatufus** [comment]
Will do

File: src/Hyperion.Akka.Integration.Tests/Hyperion.Akka.Integration.Tests.csproj [hunk 2]
```diff
@@ -0,0 +1,30 @@
+<Project Sdk="Microsoft.NET.Sdk">
```
Comment (Aaronontheweb) [inline src/Hyperion.Akka.Integration.Tests/Hyperion.Akka.Integration.Tests.csproj:1]: Probably need to have this reference `common.props`

Comment (Arkatufus) [reply src/Hyperion.Akka.Integration.Tests/Hyperion.Akka.Integration.Tests.csproj:1]: Good point.

**Review by Aaronontheweb — APPROVED** [review]
LGTM
