### PR TITLE
Fix cross framework incompatibility for System.Drawing.Color

### LINKED ISSUE #117: Cannot deserialize types when simplified qualified name is not resolvable by .NET framework
To reproduce, add this test in Hyperion.Tests:

        [Fact]
        public void CanSerializeColor()
        {
		var expected = Color.Aquamarine;
	        Serialize(expected);
	        Reset();
	        var actual = Deserialize<Color>();
	        Assert.Equal(expected, actual);
        }

This test in all the .NET core versions will pass but not the one in .NET framework.
The reason is that "System.Drawing.Color, System.Drawing" is not a fully qualified type name in .NET framework.

### PR DESCRIPTION
**Pull request by Arkatufus**
Closes #117 
Closes #206

### CODE REVIEW

File: src/Hyperion/Extensions/TypeEx.cs [hunk 1]
```diff
@@ -123,6 +123,11 @@ private static Type GetTypeFromManifestName(Stream stream, DeserializerSession s
                 {
                     shortName = shortName.Replace("System.Private.CoreLib,%core%", "mscorlib,%core%");
                 }
+                
+                if (shortName.Contains("System.Drawing.Primitives"))
```
Comment (Aaronontheweb) [inline src/Hyperion/Extensions/TypeEx.cs:127]: Ah, this is another case of where a single namespace was changed between .NET framework  and .NET core?

Comment (Arkatufus) [reply src/Hyperion/Extensions/TypeEx.cs:127]: They decided that structs are primitives and moved all structs inside `System.Drawing` into `System.Drawing.Primitives`

File: src/Hyperion.Tests/CrossFrameworkSerializationTests.cs [hunk 2]
```diff
@@ -19,9 +21,21 @@ public class CrossFrameworkSerializationTests
...
             _originalMixedObject = CrossFrameworkInitializer.InitMixed();
+
+            // Demonstrating the use of custom dll package name override
+            // to convert netcore System.Drawing.Primitives to netfx 
+            // System.Drawing package.
+            #if NETFX
+            _serializer = new Serializer(new SerializerOptions(
+                packageNameOverrides: new List<CrossPlatformPackageNameOverride>
+                {
+                    new CrossPlatformPackageNameOverride("System.Drawing.Primitives", ".Primitives", "")
```
Comment (Aaronontheweb) [inline src/Hyperion.Tests/CrossFrameworkSerializationTests.cs:34]: So how does this work exactly @Arkatufus ? What's the formula for substituting names in one package for another?

Comment (Arkatufus) [reply src/Hyperion.Tests/CrossFrameworkSerializationTests.cs:34]: The first string is the "fingerprint", the unique string that indicates the wrong package name. It is matched using `string.Contain`.
The second string is the string pattern that needs to be replaced.
The third is the string to replace it with.

In this example, "if the package name contains the string `System.Drawing.Primitives`, replace `.Primitives` with an empty string.

Comment (Aaronontheweb) [reply src/Hyperion.Tests/CrossFrameworkSerializationTests.cs:34]: How could we make that more intuitive?

Comment (Arkatufus) [reply src/Hyperion.Tests/CrossFrameworkSerializationTests.cs:34]: I don't know, any ideas?

Comment (Aaronontheweb) [reply src/Hyperion.Tests/CrossFrameworkSerializationTests.cs:34]: Think passing in a `Func<string,string>` predicate would make more sense? Leave it up to the user how to transform the name?

Comment (Arkatufus) [reply src/Hyperion.Tests/CrossFrameworkSerializationTests.cs:34]: Sounds good, I'll make the changes

Comment (Arkatufus) [reply src/Hyperion.Tests/CrossFrameworkSerializationTests.cs:34]: oh... I just remembered... we can't do that, it has to be a string, because this will have to be configurable from hocon

Comment (Aaronontheweb) [reply src/Hyperion.Tests/CrossFrameworkSerializationTests.cs:34]: We can always pass in a `Setup` for this for Hyperion just like we did for Newtonsoft.Json .

Comment (Aaronontheweb) [reply src/Hyperion.Tests/CrossFrameworkSerializationTests.cs:34]: And you can add a layer that translates HOCON into these delegates too but for this level of customization passing in an array of typed functions is probably better.

File: src/Hyperion/Extensions/TypeEx.cs [hunk 3]
```diff
@@ -118,18 +118,16 @@ private static Type GetTypeFromManifestName(Stream stream, DeserializerSession s
...
-#if NETSTANDARD
-                if (shortName.Contains("mscorlib,%core%"))
+                var overrides = session.Serializer.Options.CrossFrameworkPackageNameOverrides;
+
+                var oldName = shortName;
+                foreach (var adapter in overrides)
                 {
-                    shortName = shortName.Replace("mscorlib,%core%", "System.Private.CoreLib,%core%");
+                    shortName = adapter(shortName);
+                    if (!ReferenceEquals(oldName, shortName))
```
Comment (Arkatufus) [inline src/Hyperion/Extensions/TypeEx.cs:127]: Optimization, bail out as soon as there is a match, we will only allow one transformation.

Comment (Aaronontheweb) [reply src/Hyperion/Extensions/TypeEx.cs:127]: I like it

File: src/Hyperion.Tests/CrossFrameworkSerializationTests.cs [hunk 4]
```diff
@@ -19,9 +21,21 @@ public class CrossFrameworkSerializationTests
...
             _originalMixedObject = CrossFrameworkInitializer.InitMixed();
+
+            // Demonstrating the use of custom dll package name override
+            // to convert netcore System.Drawing.Primitives to netfx 
+            // System.Drawing package.
+            #if NETFX
+            _serializer = new Serializer(new SerializerOptions(
+                packageNameOverrides: new List<Func<string, string>>
+                {
+                    str => str.Contains("System.Drawing.Primitives") ? str.Replace(".Primitives", "") : str
```
Comment (Aaronontheweb) [inline src/Hyperion.Tests/CrossFrameworkSerializationTests.cs:34]: LGTM

File: src/Hyperion/SerializerOptions.cs [hunk 5]
```diff
@@ -16,6 +16,22 @@ namespace Hyperion
 {
     public class SerializerOptions
     {
+        internal static List<Func<string, string>> DefaultPackageNameOverrides()
+        {
+            return new List<Func<string, string>>
+            {
+#if NET45
+                str => str.Contains("System.Private.CoreLib,%core%")
```
Comment (Aaronontheweb) [inline src/Hyperion/SerializerOptions.cs:24]: LGTM

**Review by Aaronontheweb — APPROVED** [review]
Looks great - this should help quite a bit with handling some of these .NET Framework vs. NET Core conversions for users who are migrating.
